# Generated by Django 3.0.5 on 2020-04-14 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
        ('users', '0002_auto_20200414_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='resume',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='resume.Resume'),
        ),
    ]
