# Generated by Django 3.0.5 on 2020-04-14 15:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vacan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='owner',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('surname', models.CharField(max_length=32)),
                ('status', models.CharField(choices=[('NLW', 'Не ищу работу'), ('LW', 'Ищу работу'), ('CO', 'Рассматриваю предложения')], default='LW', max_length=3)),
                ('salary', models.IntegerField()),
                ('grade', models.CharField(choices=[('IN', 'Стажер'), ('JR', 'Джуниор'), ('ML', 'Миддл'), ('SR', 'Синьор'), ('LD', 'Лид')], default='JR', max_length=2)),
                ('education', models.CharField(choices=[('BL', 'Бакалавриат'), ('IN', 'Специалитет'), ('MR', 'Магистратура'), ('PH', 'Кандидат наук'), ('DR', 'Доктор наук'), ('NG', 'Нет специального образования, но богатый опыт')], default='IN', max_length=2)),
                ('experience', models.IntegerField()),
                ('portfolio', models.TextField()),
                ('specialty', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to='vacan.Speciality')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('written_username', models.CharField(max_length=32)),
                ('written_phone', models.CharField(max_length=12)),
                ('written_cover_letter', models.TextField(blank=True)),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
                ('vacancy', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='vacan.Vacancy')),
            ],
        ),
        migrations.AddField(
            model_name='vacancy',
            name='application',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to='vacan.Application'),
        ),
    ]
