# Generated by Django 3.0.5 on 2020-04-14 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
        ('users', '0003_auto_20200414_1744'),
        ('vacan', '0002_auto_20200414_1556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='specialty',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='user',
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='application',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to='application.Application'),
        ),
        migrations.DeleteModel(
            name='Application',
        ),
        migrations.DeleteModel(
            name='Resume',
        ),
    ]
